from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from .gitmeta import detect_git_context
from .util import ensure_dir, safe_write, write_text_if_changed

SHARED_CARD_KINDS = [
    "current-state",
    "patterns",
    "decision-log",
    "testing",
    "ux-flows",
    "failure-memory",
    "harness-rules",
    "quality-bar",
]

AGENT_MEMORY_ROLES = [
    "why-analyst",
    "root-cause-analyst",
    "harness-profiler",
    "solution-architect",
    "test-strategist",
    "env-doctor",
    "test-implementer",
    "task-implementer",
    "task-checker",
    "verify-reducer",
    "ux-reviewer",
    "architecture-reviewer",
    "security-reviewer",
    "performance-reviewer",
]


def knowledge_root(root: Path) -> Path:
    return root / "docs" / "xlfg" / "knowledge"


def cards_root(root: Path) -> Path:
    return knowledge_root(root) / "cards"


def events_root(root: Path) -> Path:
    return knowledge_root(root) / "events"


def views_root(root: Path) -> Path:
    return knowledge_root(root) / "_views"


def agent_memory_root(root: Path) -> Path:
    return knowledge_root(root) / "agent-memory"


def service_context_path(root: Path) -> Path:
    return knowledge_root(root) / "service-context.md"


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def _first_heading(text: str, fallback: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip() or fallback
        if line:
            return line[:120]
    return fallback


def _entry_sort_key(path: Path, current_branch_slug: Optional[str], default_branch_slug: Optional[str]) -> Tuple[int, int, str]:
    branch = None
    try:
        branch = path.parent.name
    except Exception:
        branch = None
    priority = 2
    if current_branch_slug and branch == current_branch_slug:
        priority = 0
    elif default_branch_slug and branch == default_branch_slug:
        priority = 1
    return (priority, 0, path.as_posix())


def ensure_knowledge_layout(root: Path) -> Dict[str, List[str]]:
    created: List[str] = []
    ensure_dir(knowledge_root(root))
    ensure_dir(cards_root(root))
    ensure_dir(events_root(root))
    ensure_dir(views_root(root))
    ensure_dir(views_root(root) / "agent-memory")
    ensure_dir(agent_memory_root(root))

    for kind in SHARED_CARD_KINDS:
        ensure_dir(cards_root(root) / kind)
        placeholder = cards_root(root) / kind / ".gitkeep"
        if safe_write(placeholder, ""):
            created.append(str(placeholder.relative_to(root)))

    for role in AGENT_MEMORY_ROLES:
        ensure_dir(agent_memory_root(root) / role / "cards")
        placeholder = agent_memory_root(root) / role / "cards" / ".gitkeep"
        if safe_write(placeholder, ""):
            created.append(str(placeholder.relative_to(root)))

    placeholder = events_root(root) / ".gitkeep"
    if safe_write(placeholder, ""):
        created.append(str(placeholder.relative_to(root)))

    return {"created": created}


def _render_card_view(
    title: str,
    edit_hint: str,
    card_paths: Sequence[Path],
    root: Path,
    include_service_context: bool = False,
) -> str:
    lines: List[str] = [
        f"# {title}",
        "",
        "_Generated local read model. Do not edit this file directly._",
        "",
        edit_hint,
        "",
    ]
    if include_service_context:
        service = _read_text(service_context_path(root)).strip()
        if service:
            lines.extend([
                "## Tracked service context",
                "",
                service,
                "",
            ])
    if not card_paths:
        lines.extend([
            "No cards yet.",
            "",
            "Run `/xlfg:compound` after a real run to promote reusable lessons into tracked cards, then rebuild views.",
            "",
        ])
        return "\n".join(lines).rstrip() + "\n"

    for path in card_paths:
        rel = path.relative_to(root)
        text = _read_text(path).strip()
        if not text:
            continue
        title = _first_heading(text, path.stem)
        lines.extend([
            f"## {title}",
            "",
            f"Source: `{rel}`",
            "",
            text,
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _iter_shared_cards(root: Path, kind: str) -> List[Path]:
    base = cards_root(root) / kind
    if not base.exists():
        return []
    return sorted([p for p in base.rglob("*.md") if p.name.lower() != "readme.md"])


def _iter_agent_cards(root: Path, role: str) -> List[Path]:
    base = agent_memory_root(root) / role / "cards"
    if not base.exists():
        return []
    return sorted([p for p in base.rglob("*.md") if p.name.lower() != "readme.md"])


def _load_event_files(root: Path) -> List[Tuple[Path, Dict[str, Any]]]:
    results: List[Tuple[Path, Dict[str, Any]]] = []
    base = events_root(root)
    if not base.exists():
        return results
    for path in sorted(base.rglob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        results.append((path, data))
    return results


def rebuild_views(root: Path) -> Dict[str, Any]:
    ensure_knowledge_layout(root)
    git_ctx = detect_git_context(root)
    current_branch_slug = git_ctx.get("branch_slug")
    default_branch_slug = git_ctx.get("default_branch_slug")
    updated: List[str] = []

    for kind in SHARED_CARD_KINDS:
        cards = sorted(
            _iter_shared_cards(root, kind),
            key=lambda p: _entry_sort_key(p, current_branch_slug, default_branch_slug),
        )
        view_path = views_root(root) / f"{kind}.md"
        content = _render_card_view(
            title=kind.replace("-", " "),
            edit_hint=f"Edit tracked cards under `docs/xlfg/knowledge/cards/{kind}/<branch-slug>/...`, then rerun `xlfg knowledge rebuild`.",
            card_paths=cards,
            root=root,
            include_service_context=(kind == "current-state"),
        )
        if write_text_if_changed(view_path, content):
            updated.append(str(view_path.relative_to(root)))

    for role in AGENT_MEMORY_ROLES:
        cards = sorted(
            _iter_agent_cards(root, role),
            key=lambda p: _entry_sort_key(p, current_branch_slug, default_branch_slug),
        )
        view_path = views_root(root) / "agent-memory" / f"{role}.md"
        content = _render_card_view(
            title=f"agent memory {role}",
            edit_hint=f"Edit tracked cards under `docs/xlfg/knowledge/agent-memory/{role}/cards/<branch-slug>/...`, then rerun `xlfg knowledge rebuild`.",
            card_paths=cards,
            root=root,
            include_service_context=False,
        )
        if write_text_if_changed(view_path, content):
            updated.append(str(view_path.relative_to(root)))

    event_rows: List[Dict[str, Any]] = []
    for path, data in _load_event_files(root):
        if not isinstance(data, dict):
            continue
        event_rows.append({"_path": str(path.relative_to(root)), **data})
    event_rows.sort(key=lambda item: (str(item.get("created_at") or ""), str(item.get("id") or item.get("_path"))), reverse=True)
    ledger_lines = [json.dumps({k: v for k, v in row.items() if k != "_path"}, sort_keys=True) for row in event_rows]
    ledger_view = views_root(root) / "ledger.jsonl"
    if write_text_if_changed(ledger_view, ("\n".join(ledger_lines) + ("\n" if ledger_lines else ""))):
        updated.append(str(ledger_view.relative_to(root)))

    worktree_view = views_root(root) / "worktree.md"
    worktree_lines = [
        "# worktree",
        "",
        "_Generated local context for the active git worktree._",
        "",
        f"- branch: `{git_ctx.get('branch') or 'detached'}`",
        f"- branch slug: `{git_ctx.get('branch_slug')}`",
        f"- default branch: `{git_ctx.get('default_branch') or 'unknown'}`",
        f"- worktree: `{git_ctx.get('worktree_name')}`",
        f"- write namespace: `{git_ctx.get('knowledge_write_namespace')}`",
        f"- write mode: `{git_ctx.get('knowledge_write_mode')}`",
        "",
        "Compounding must create immutable cards and event files, then rebuild local views. Do not hand-edit shared rollup docs on feature branches.",
        "",
    ]
    if write_text_if_changed(worktree_view, "\n".join(worktree_lines)):
        updated.append(str(worktree_view.relative_to(root)))

    return {
        "updated": updated,
        "shared_card_kinds": SHARED_CARD_KINDS,
        "agent_memory_roles": AGENT_MEMORY_ROLES,
        "event_count": len(event_rows),
        "git_context": git_ctx,
    }
